added notification system\toolbar
ZayetsA/Survay pull request #1
Opened 2021-05-06 11:41 UTC by ZayetsA

added notification system, toolbar, fixed some problems

2021-05-06 13:04 UTC, VladimirOnix requested changes

2021-05-06 13:04 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/adapter/ViewPagerAdapter.kt
> +    private var fragmentList1: ArrayList<Fragment> = ArrayList()
Why 1 suffix needed here ?

2021-05-06 13:04 UTC, VladimirOnix commented on app/src/main/java/com/onix/internship/survay/login/LoginFragment.kt
> +    private fun removeErrorsDisplayingListener() {
You don't needed error on-the-fly checking. Use binding, collect error in viewModel and show it in view through bindingAdapter

2021-05-13 08:58 UTC, VladimirOnix approved these changes

2021-05-13 09:24 UTC, TAEKsCode requested changes

2021-05-13 09:24 UTC, TAEKsCode commented on app/src/main/java/com/onix/internship/survay/login/LoginFragment.kt
> +                loginViewModel.doneNavigationToUserDetails()
Для того, чтобы избавиться от подобных штук, как раз и был SingleLiveEvent, ему не надо обнулять значение, навигация через него выполнится 1 раз, потому что single и тебе не придётся писать рукописные коллбеки по типу этого

2021-05-13 09:24 UTC, TAEKsCode commented on app/src/main/java/com/onix/internship/survay/login/LoginViewModel.kt
>      private val uiScope = CoroutineScope(Dispatchers.Main + viewModelJob)
Есть viewModelScope, это то же самое, что ты написал

2021-05-13 09:24 UTC, TAEKsCode commented on app/src/main/java/com/onix/internship/survay/signup/SignupViewModel.kt
> +    AndroidViewModel(application) {
Зачем андроид вью модел? Он нужен только для того, чтобы во вью модели появился контекст, а это не правильно по МВВМ. Просто используй ViewModel

2021-05-13 09:24 UTC, TAEKsCode commented on app/src/main/java/com/onix/internship/survay/userlist/UserListFragment.kt
>          val dao = UserDatabase.getInstance(application).userDatabaseDao
Было:
val application = requireNotNull(this.activity).application
val dao = UserDatabase.getInstance(application).userDatabaseDao
Должно быть: 
val dao = UserDatabase.getInstance(requireContext()).userDatabaseDao
Так запись лучше читается и контекст тебе дальше не нужен(во вью моделе тоже)

2021-05-13 09:24 UTC, TAEKsCode commented on app/src/main/res/values/dimens.xml
>      <dimen name="margin_30">30dp</dimen>
Нейминги нужно привязывать к контексту. Если у тебя этот маржин_30 на одном экране делает отступ между кнопками, а на втором он делает отступы в айтеме списка например и ты захочешь изменить в первом, но не захочешь менять во втором, то что тогда? Новый димен с названием item_margin_30, а потом не 30, а надо уже 20. Короче нейминг по типу appbar_padding_top сойдёт, главное в названии - писать контекст, куда этот маржин принадлежит

2021-05-15 11:12 UTC, merged